### ISSUE TITLE
Seri bir şekilde tıklayınca kartlar açık kalıyor

### ISSUE THREAD

**Issue by buraksakalli** [ozlemts/catMatchingGame#1]
![Screenshot_3](https://user-images.githubusercontent.com/10114716/71593908-dafde980-2b46-11ea-917c-0bda291d37be.jpg)

Seri bir şekilde tıklayınca tıklanılan her üç karttan ilki açık kalıyor

**Comment by ozlemts** [comment]
Timeout süresince diğer kartların click eventlerini engelledim, çözüldü. Teşekkür ederim.
